import Foundation
import Security

public enum ConnectError: Error, LocalizedError {
    case message(String)
    public var errorDescription: String? {
        if case .message(let m) = self { return m }
        return nil
    }
}

/// This install's persistent, self-signed TLS identity (ECDSA P-256).
///
/// The private key is generated by the Security framework and kept in the
/// user's login keychain (it is never exported); the certificate is assembled
/// by [`X509`] and stored next to it. Created once and reused forever:
/// replacing it would invalidate every pairing (the peers' pins would no
/// longer match) — same recovery story as the desktop: forget and pair again.
public final class TLSIdentity {
    public let identity: SecIdentity
    public let certificateDER: Data
    public let fingerprint: String

    private static let label = "Blue Connect Identity"

    private init(identity: SecIdentity, certificate: SecCertificate) {
        self.identity = identity
        self.certificateDER = SecCertificateCopyData(certificate) as Data
        self.fingerprint = Sas.fingerprint(certificateDER)
    }

    public static func loadOrCreate() throws -> TLSIdentity {
        if let existing = loadExisting() { return existing }
        return try create()
    }

    private static func loadExisting() -> TLSIdentity? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassCertificate,
            kSecAttrLabel as String: label,
            kSecReturnRef as String: true,
        ]
        var item: CFTypeRef?
        guard SecItemCopyMatching(query as CFDictionary, &item) == errSecSuccess, let ref = item else { return nil }
        let cert = ref as! SecCertificate // swiftlint:disable:this force_cast
        var ident: SecIdentity?
        // Finds the matching private key in the keychain; fails if it was deleted.
        guard SecIdentityCreateWithCertificate(nil, cert, &ident) == errSecSuccess, let identity = ident else { return nil }
        return TLSIdentity(identity: identity, certificate: cert)
    }

    private static func create() throws -> TLSIdentity {
        // Remove leftovers of a half-finished earlier attempt so lookups stay unambiguous.
        SecItemDelete([kSecClass as String: kSecClassCertificate, kSecAttrLabel as String: label] as CFDictionary)
        SecItemDelete([kSecClass as String: kSecClassKey, kSecAttrLabel as String: label] as CFDictionary)

        let keyAttrs: [String: Any] = [
            kSecAttrKeyType as String: kSecAttrKeyTypeECSECPrimeRandom,
            kSecAttrKeySizeInBits as String: 256,
            kSecAttrIsPermanent as String: true,
            kSecAttrLabel as String: label,
        ]
        var err: Unmanaged<CFError>?
        guard let privateKey = SecKeyCreateRandomKey(keyAttrs as CFDictionary, &err) else {
            throw ConnectError.message("Could not create the TLS key: \(err?.takeRetainedValue().localizedDescription ?? "unknown error")")
        }
        let certificate = try makeCertificate(privateKey: privateKey)

        let status = SecItemAdd([
            kSecClass as String: kSecClassCertificate,
            kSecValueRef as String: certificate,
            kSecAttrLabel as String: label,
        ] as CFDictionary, nil)
        guard status == errSecSuccess || status == errSecDuplicateItem else {
            throw ConnectError.message("Could not store the TLS certificate in the keychain (OSStatus \(status))")
        }
        var ident: SecIdentity?
        guard SecIdentityCreateWithCertificate(nil, certificate, &ident) == errSecSuccess, let identity = ident else {
            throw ConnectError.message("Could not build a TLS identity from the new key and certificate")
        }
        return TLSIdentity(identity: identity, certificate: certificate)
    }

    /// Builds + signs the self-signed certificate for `privateKey`. Separate
    /// (and `internal`) so tests can exercise it with a throw-away,
    /// non-keychain key.
    static func makeCertificate(privateKey: SecKey) throws -> SecCertificate {
        guard let publicKey = SecKeyCopyPublicKey(privateKey),
              let point = SecKeyCopyExternalRepresentation(publicKey, nil) as Data? else {
            throw ConnectError.message("Could not read the public key")
        }
        var serial = [UInt8](repeating: 0, count: 8)
        guard SecRandomCopyBytes(kSecRandomDefault, serial.count, &serial) == errSecSuccess else {
            throw ConnectError.message("Could not generate a certificate serial number")
        }
        let now = Date()
        let tbs = X509.tbsCertificate(
            commonName: "blue-connect.local",
            publicKeyPoint: [UInt8](point),
            serial: serial,
            notBefore: now.addingTimeInterval(-24 * 3600),
            notAfter: now.addingTimeInterval(10 * 365 * 24 * 3600)
        )
        var err: Unmanaged<CFError>?
        guard let signature = SecKeyCreateSignature(privateKey, .ecdsaSignatureMessageX962SHA256, Data(tbs) as CFData, &err) as Data? else {
            throw ConnectError.message("Could not sign the certificate: \(err?.takeRetainedValue().localizedDescription ?? "unknown error")")
        }
        let der = X509.certificate(tbs: tbs, signatureDER: [UInt8](signature))
        guard let cert = SecCertificateCreateWithData(nil, Data(der) as CFData) else {
            throw ConnectError.message("The generated certificate was rejected by the Security framework")
        }
        return cert
    }
}
