import { WindowItem, TrayEntry, CalDay, BluePanel } from "./panel.slint";
import { AppItem, FsAppItem, CompactAppMenu, FullscreenLauncher } from "./app_menu.slint";
import { BlueSettings } from "./settings.slint";
import { ActionItem, PopupItem, CenterItem, NotificationCenter, NotificationOverlay } from "./notifications.slint";
import { DockEntry, BlueDock } from "./dock.slint";

// Re-eksportuj wszystko żeby include_modules!() widział te typy
export { WindowItem, TrayEntry, CalDay, BluePanel }
export { AppItem, FsAppItem, CompactAppMenu, FullscreenLauncher }
export { BlueSettings }
export { ActionItem, PopupItem, CenterItem, NotificationCenter, NotificationOverlay }
export { DockEntry, BlueDock }
